# Generated by Django 6.1 on 2026-08-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Studio', 'Studio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='action_type',
            field=models.CharField(choices=[('Location', 'Location'), ('Achat', 'Achat'), ('Visite', 'Visite')], default='Louer', max_length=20),
        ),
    ]
